[package]
name = "kluars"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.5", features = ["derive"] }
mlua = { version = "0.9.1", features = ["serialize", "luajit"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
