name: Main kluars CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install luaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install luaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit

      - name: Run tests
        run: cargo test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install luaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit

      - run: cargo build
